version: '3.7'

services:
  phpmyadmin:
    container_name: s5bp_phpmyadmin
    build: ./docker/phpmyadmin
    depends_on:
      - mysql
    ports:
      - '${PHPMYADMIN_PORT_80:-81}:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    networks:
      - s5bp-app-network
