version: '3.7'

services:
  phpmyadmin:
    container_name: s5bp_phpmyadmin
    build: ./docker/phpmyadmin
    depends_on:
      - mysql
    ports:
      - '${PHPMYADMIN_PORT_80:-81}:80'
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
    networks:
      - s5bp-app-network

  mongo-express:
    container_name: s5bp_mongo_express
    build: ./docker/mongo-express
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD:-rootpassword}
    ports:
      - '${MONGO_EXPRESS_PORT_8081:-8081}:8081'
    networks:
      - s5bp-app-network
