version: '3.7'

services:
  # For easier DB managament, let's also add PHPMyAdmin
  phpmyadmin:
    container_name: cw_phpmyadmin
    build: ./web/docker/phpmyadmin
    depends_on:
      - mysql
    ports:
      - '${PHPMYADMIN_PORT_80:-81}:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    networks:
      - cw-app-network
