monolog:
    handlers:
# TODO: not working. It somehow only clogs up the container
#        es:
#            type: service
#            id: Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
