easy_admin:
    site_name: '%app.name% Admin'
    entities:
        User:
            class: App\Entity\User
            label: 'Users'
            disabled_actions: [ 'new', 'delete' ]
            list:
                fields:
                    - id
                    - username
                    - email
                    - roles
                    - countryCode
                    - city
                    - private
                    - locked
                    - lockedReason
                    - createdAt
                    - updatedAt
            form:
                fields:
                    - username
                    - email
                    - property: plainPassword
                      type: password
                    - property: roles
                      type: choice
                      type_options:
                          mapped: true
                          expanded: true
                          multiple: true
                          choices:
                              'Super admin': ROLE_SUPER_ADMIN
                              'Admin': ROLE_ADMIN
                              'User moderator': ROLE_USER_MODERATOR
                              'User': ROLE_USER
                    - property: countryCode
                      type: 'country'
                    - city
                    - imageFileUrl
                    - private
                    - locked
                    - lockedReason
                    - createdAt
                    - updatedAt
                    - emailConfirmedAt

        UserAction:
            class: App\Entity\UserAction
            label: 'User actions'
            disabled_actions: [ 'new', 'edit', 'delete' ]
            list:
                fields:
                    - id
                    - user
                    - message
                    - key
                    - ip
                    - userAgent
                    - sessionId
                    - property: data
                      template: 'admin/fields/user_action_data.html.twig'
                    - createdAt

        UserDevice:
            class: App\Entity\UserDevice
            label: 'User Devices'
            disabled_actions: [ 'new', 'edit', 'delete' ]

        UserOauthProvider:
            class: App\Entity\UserOauthProvider
            label: 'User OAuth Providers'
            disabled_actions: [ 'new', 'edit', 'delete' ]

        UserTfaMethod:
            class: App\Entity\UserTfaMethod
            label: 'User TFA Methods'
            disabled_actions: [ 'new', 'edit', 'delete' ]

        UserTfaRecoveryCode:
            class: App\Entity\UserTfaRecoveryCode
            label: 'User TFA Recovery Codes'
            disabled_actions: [ 'new', 'edit', 'delete' ]

        UserNotification:
            class: App\Entity\UserNotification
            label: 'User Notifications'
            disabled_actions: [ 'new', 'edit', 'delete' ]

        UserBlock:
            class: App\Entity\UserBlock
            label: 'User Blocks'
            disabled_actions: [ 'new', 'edit', 'delete' ]

        UserFollower:
            class: App\Entity\UserFollower
            label: 'User Followers'
            disabled_actions: [ 'new', 'edit', 'delete' ]

        UserPoint:
            class: App\Entity\UserPoint
            label: 'User Points'
            disabled_actions: [ 'new', 'edit', 'delete' ]

        UserExport:
            class: App\Entity\UserExport
            label: 'User Exports'
            disabled_actions: [ 'new', 'edit', 'delete' ]

        Thread:
            class: App\Entity\Thread
            label: 'Threads'
            disabled_actions: [ 'new', 'edit', 'delete' ]

        ThreadUser:
            class: App\Entity\ThreadUser
            label: 'Thread Users'
            disabled_actions: [ 'new', 'edit', 'delete' ]

        ThreadUserMessage:
            class: App\Entity\ThreadUserMessage
            label: 'Thread User Messages'
            disabled_actions: [ 'new', 'edit', 'delete' ]
