easy_admin:
    site_name: '%app.name% Admin'
    entities:
        User:
            class: App\Entity\User
            label: 'Users'
            disabled_actions: [ 'new', 'delete' ]
            list:
                fields:
                    - id
                    - username
                    - email
                    - roles
                    - countryCode
                    - city
                    - private
                    - locked
                    - lockedReason
                    - createdAt
                    - updatedAt
            form:
                fields:
                    - username
                    - email
                    - property: plainPassword
                      type: password
                    - property: roles
                      type: choice
                      type_options:
                          mapped: true
                          expanded: true
                          multiple: true
                          choices:
                              'Super admin': ROLE_SUPER_ADMIN
                              'Admin': ROLE_ADMIN
                              'User moderator': ROLE_USER_MODERATOR
                              'User': ROLE_USER
                    - property: countryCode
                      type: 'country'
                    - city
                    - imageFileUrl
                    - private
                    - locked
                    - lockedReason
                    - createdAt
                    - updatedAt
                    - emailConfirmedAt

        UserAction:
            class: App\Entity\UserAction
            label: 'User actions'
            disabled_actions: [ 'new', 'edit', 'delete' ]
            list:
                fields:
                    - id
                    - user
                    - message
                    - key
                    - ip
                    - userAgent
                    - sessionId
                    - property: data
                      template: 'admin/fields/user_action_data.html.twig'
                    - createdAt

        UserOauthProvider:
            class: App\Entity\UserOauthProvider
            label: 'User OAuth providers'
            disabled_actions: [ 'new', 'edit', 'delete' ]

        UserNotification:
            class: App\Entity\UserNotification
            label: 'User notifications'
            disabled_actions: [ 'new', 'edit', 'delete' ]

        UserFollower:
            class: App\Entity\UserFollower
            label: 'User followers'
            disabled_actions: [ 'new', 'edit', 'delete' ]

        UserPoint:
            class: App\Entity\UserPoint
            label: 'User points'
            disabled_actions: [ 'new', 'edit', 'delete' ]

        UserExport:
            class: App\Entity\UserExport
            label: 'User exports'
            disabled_actions: [ 'new', 'edit', 'delete' ]
