flysystem:
    storages:
        user_export.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/uploads/users/exports'
        user_image.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/uploads/users/images'
