framework:
    messenger:
        failure_transport: failed

        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed'
            sync: 'sync://'

        routing:
            'App\Message\UserExportRequest': async
            'App\Message\ThreadUserMessage': async
