vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        user_export:
            uri_prefix: /uploads/users/exports
            upload_destination: user_export.storage
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        user_image:
            uri_prefix: /uploads/users/images
            upload_destination: user_image.storage
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
