vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /uploads/users/images
            upload_destination: '%kernel.project_dir%/public/uploads/users/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        user_export:
            uri_prefix: /uploads/users/exports
            upload_destination: '%kernel.project_dir%/public/uploads/users/exports'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
