parameters:
    # General
    app.name: 'Symfony5 boilerplate'
    app.twitter_handle: 'corcosoft'
    app.description: 'Just your usual symfony5 boilerplate'
    app.keywords: 'symfony5 boilerplate'
    app.mailer_from: Corcosoft <mailer@corcosoft.com>
    app.mailer_to: Borut <bobalazek124@gmail.com>
    app.roles:
        ROLE_USER: User
        ROLE_STAFF: Staff
        ROLE_MODERARATOR: Moderator
        ROLE_ADMIN: Admin
        ROLE_SUPER_ADMIN: Super Admin

    # WS
    app.ws.url: 'ws://localhost:%env(WS_PORT_8080)%'

    # Credentials
    app.oauth.facebook:
        id: '%env(OAUTH_FACEBOOK_ID)%'
        secret: '%env(OAUTH_FACEBOOK_SECRET)%'
        version: '%env(OAUTH_FACEBOOK_VERSION)%'
        scope: '%env(OAUTH_FACEBOOK_SCOPE)%'
    app.oauth.google:
        id: '%env(OAUTH_GOOGLE_ID)%'
        secret: '%env(OAUTH_GOOGLE_SECRET)%'
    app.google.recaptcha.site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

    # TFA
    app.tfa.allowed_routes:
        - null # error
        - auth.logout
        - auth.login.tfa
