framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true

    session:
        cookie_secure: auto
        cookie_samesite: lax
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler

    php_errors:
        log: true
